# Generated by Django 5.2 on 2025-04-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Designer', 'Designer'), ('Manager', 'Manager'), ('Tester', 'Tester'), ('HR', 'HR')], default='Developer', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
